### PR TITLE
Updating documentation and build tools

### PR DESCRIPTION
**Pull request by vassad**
Hey!

Updated the documentation README.MD

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toktok/8)

### CODE REVIEW

**Comment by iphydf** [comment]
Thanks :) you may want to rebase and change the author of the two vknyazev commits so they are correctly attributed to your github user.

**Comment by iphydf** [comment]
Perhaps you can just squash all the commits into one.

**Comment by vassad** [comment]
I see, will try)

**Comment by vassad** [comment]
Tried to merge into one commit, seems to be ok)

**Comment by vassad** [comment]
Added the vknyazev email to my account and verified it, but CLA seems to still show that i've not signed it for vknyazev...

**Comment by robinlinden** [comment]
For merging them into one commit, use `git rebase -i HEAD~5` (5 in this case because you want to combine the last 5 commits.) Then pick the first commit and squash the rest. You will have to push with `--force` since you're rewriting history.
You might also want to add spaces between the markdown and titles, so they look like `## Installation`.

**Comment by vassad** [comment]
@robinlinden So I've followed your instructions and squashed all the commits to one, including ## spaces. But there is still vknyazev user here. Maybe we need to create new PR?

**Pull request closed without merging**
